property:
  gpu-id: 0
  net-scale-factor: 0.0039215697906911373
  model-color-format: 0
  custom-network-config: yolov8l.cfg
  model-file: yolov8l.wts
  model-engine-file: ../model/model_b1_gpu0_int8.engine
  int8-calib-file: calib.table
  labelfile-path: ../model/labels.txt
  batch-size: 1
  network-mode: 2
  num-detected-classes: 80
  interval: 0
  gie-unique-id: 1
  process-mode: 1
  network-type: 0
  cluster-mode: 2
  maintain-aspect-ratio: 1
  symmetric-padding: 1
  parse-bbox-func-name: NvDsInferParseYolo
  custom-lib-path: ../plugin/libnvdsinfer_custom_impl_Yolo.so
  engine-create-func-name: NvDsInferYoloCudaEngineGet

class-attrs-all:
  nms-iou-threshold: 0.45
  pre-cluster-threshold: 0.25
  topk: 300
